name: Build binaries for release

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, freebsd, linux, openbsd, windows]
        goarch: ["386", amd64, arm, arm64]
        exclude:  
          - goarch: [arm, arm64]
            goos: darwin
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.GH_PAT }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.16"
        md5sum: false
        sha256sum: true
        project_path: "./"
        binary_name: "ego"
        extra_files: LICENSE README.md
